name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  maboss_conda:
    name: Anaconda package
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: conda install conda-build anaconda-client
      
    - name: Build Anaconda package
      run: |
        conda build libmaboss

    - name: Upload cMaBoSS Ananconda package
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --force;
    