name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
 
  conda_maboss:
    name: Build Conda MaBoSS package
    runs-on: macos-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Installing conda-build      
      run: conda install conda-build anaconda-client

    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm    
    
    - name: Build MaBoSS Anaconda package
      run: |
        conda build libmaboss
           
    - name: Upload MaBoSS to Anaconda cloud
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 